#!/bin/sh

set -e

lb config noauto \
    -a amd64 \
    -k amd64 \
    --distribution jessie \
    --archive-areas "main contrib non-free" \
    --checksums sha256 \
    --debian-installer live \
    --debian-installer-distribution jessie \
    --firmware-chroot true \
    --firmware-binary true \
    --bootappend-live "boot=live components locales=de_DE.UTF-8 keyboard-layouts=de nosplash" \
    --iso-publisher robin-eyerdam.de \
    --parent-mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --parent-mirror-binary http://ftp.de.debian.org/debian/ \
    --security true \
    --updates true \
    --verbose \
	"${@}"
